### PR TITLE
Fix whitespace in logit docstring

### PR DESCRIPTION
**Pull request by jishnub**
Minor adjustment to spaces in the docstring of `logit`. Hopefully, this will separate the word from the equation, making it easy to read

### CODE REVIEW

**Comment by devmotion** [comment]
Thanks! Did you check locally that it works as intended?

**Comment by jishnub** [comment]
No, I haven't yet, will update after checking

**Comment by devmotion** [comment]
I just checked locally and unfortunately it doesn't seem to fix the issue:
image

**Comment by devmotion** [comment]
I fixed it by reformulating the docstring:
image

**Comment by devmotion** [comment]
Thanks a lot @jishnub!

**Pull request merged**
