### PR TITLE
add `logabssinh`

### LINKED ISSUE #69: `logabssinh`
LogExpFunctions already has `logcosh`. normally, when those terms appear, there is also `log(abs(sinh))` terms. In my specific field, that term appear in natural-gas properties:
image

logsinh can be expressed in terms of `LogExpFunctions.log1mexp`:
```
function logabssinh(x::Real)
    abs_x = abs(x)
    return abs_x + log1mexp(- 2 * abs_x) - IrrationalConstants.logtwo
end
```
Is it ok to have this function here?

### PR DESCRIPTION
**Pull request by longemen3000**
closes #69 . Implementation, chainrules and tests done

### CODE REVIEW

**Review by devmotion — COMMENTED** [review]
Looks mainly good, thank you!

Can you add it to the docs and bump the version number?

**Review by devmotion — COMMENTED** [review]
One additional point that I missed yesterday: Can you also add a test for the ChainRules definition in the respective test file?

**Review by devmotion — APPROVED** [review]
Looks good to me!

**Comment by oscardssmith** [comment]
One last thing is that this will be pretty inaccurate when the output is near zero. I'm not sure if it matters, but I figured I would bring it up.

**Comment by longemen3000** [comment]
in my particular case, the more interesting points are near x = 1, but it is a valid point.

**Pull request merged**
